# seeds for communities

communities = [
  {
    name: "Comunidad Santiaguina",
    about: "Somos estudiantes, egresados, profesores, trabajadores y personas que nos sentimos parte de la Universidad Santiago de Cali. Somos santiaguinos, somos USC.",
    email: "",
    website: "http://usc.edu.co",
    phone: "",
    facebook: "https://www.facebook.com/usantiagodecali/",
    instagram: "https://www.instagram.com/usantiagodecali/",
    twitter: "https://twitter.com/usantiagodecali",
    comuna_id: 19,
    image: 'images/com-1'
  },
  {
    name: "Somos Lobos Rugby",
    about: "Somos lobos y lobas, la comunidad de lobos rugby club y lobos univalle. Somos jugadores, entrenadores, exjugadores, hinchas y quienes admiramos y apoyamos el progreso del equipo desde todas sus categorías y representaciones...Y sepan que solo muero si ustedes van aflojando porque el que murió peleando vive en cada compañer@. Venceremos!",
    email: "",
    website: "",
    phone: "317 5571203",
    facebook: "https://www.facebook.com/LobosRC/",
    instagram: "https://www.instagram.com/lobos_rugbyclub/",
    twitter: "https://twitter.com/LobosRugbycali",
    comuna_id: 19,
    image: 'images/com-2'
  },
  {
    name: "Niños, Niñas, Adolescentes y Jóvenes Gestores de Paz - Cali",
    about: "Movimiento Nacional de niños, niñas, adolescentes y jóvenes gestores de paz de Santiago de Cali. Somos personas que le aportamos a la construcción de una cultura de paz desde nuestros entornos, haciendo actividades que permitan vivenciar experiencias de transformación social y que reivindican los derechos y buenas prácticas niños, niñas y jóvenes en lugares con altos índices de problemáticas sociales.",
    email: "",
    website: "https://www.wvi.org/es/GestoresdePaz",
    phone: "",
    facebook: "",
    instagram: "",
    twitter: "https://twitter.com/SoyGestordePaz",
    comuna_id: 14,
    image: 'images/com-3'
  },
  {
    name: "Distrito Rugby",
    about: "Comunidad de personas simpatizantes por el desarrollo y difusión del rugby, que empieza promocionando este apasionante deporte en el Distrito de Aguablanca de Santiago de Cali. Creemos que el rugby es un estilo de vida y herramienta que aporta y forja importantes valores en el desarrollo de las personas que practican esta disciplina deportiva.",
    email: "",
    website: "http://distritorugby.herokuapp.com/",
    phone: "",
    facebook: "",
    instagram: "",
    twitter: "",
    comuna_id: 13,
    image: 'images/com-4'
  },
  {
    name: "Rugby Valle",
    about: "Buscamos promover el desarrollo del rugby en el Valle de Cauca. Somos la comunidad que práctica y promueve el rugby en todo el departamento.",
    email: "",
    website: "http://rugbyvalle.co/",
    phone: "",
    facebook: "https://www.facebook.com/LVRrugby/?epa=SEARCH_BOX",
    instagram: "https://www.instagram.com/rugbyvalle/",
    twitter: "https://twitter.com/LVR_rugby",
    comuna_id: 19,
    image: 'images/com-5'
  },
  {
    name: "Soy Sultán",
    about: "Apoyamos a Sultanes Rugby Club",
    email: "sultanes.rc@hotmail.com",
    website: "http://www.sultanesrugby.club/",
    phone: "311 3007050",
    facebook: "https://www.facebook.com/SultanesRugby/",
    instagram: "https://www.instagram.com/sultanes_rc/",
    twitter: "",
    comuna_id: 18,
  },
  {
    name: "Buziracas Rugby",
    about: "Apoyamos el desarrollo del rugby femenino, somos buziracas hu-hu-hu!",
    email: "buziracasrugbyfem@gmail.com",
    website: "",
    phone: "",
    facebook: "https://www.facebook.com/buziracasrugbyclub/",
    instagram: "https://www.instagram.com/buziracas_rugby/",
    twitter: "",
    comuna_id: 17,
  },
  {
    name: "Phalanx rugby",
    about: "Somos la comunidad de Phalanx Rugby Club. Sentimiento azul y negro. Las heridas sanan, los huesos soldan, la moral se levanta.",
    email: "",
    website: "",
    phone: "316 4212096",
    facebook: "https://www.facebook.com/Phalanxrc/",
    instagram: "https://www.instagram.com/phalanxrugbyclub/",
    twitter: "",
    comuna_id: 17,
  },
  {
    name: "Tikunas Rugby",
    about: "Somos la comunidad de personas que apoya al club de rugby Tikunas. Equipo de rugby femenino que impulsa el desarrollo de este deporte en el sur y oriente de la ciudad. Hasta el alma",
    email: "",
    website: "",
    phone: "318 4031176",
    facebook: "https://www.facebook.com/TikunasRugbyClubCali/",
    instagram: "https://www.instagram.com/tikunasrugby/",
    twitter: "",
    comuna_id: 19,
  },
  {
    name: "Amapolas rugby",
    about: "Somos la comunidad que apoya a Amapolas Rugby Club. Equipo de rugby femenino que entrena en el norte de la ciudad.",
    email: "",
    website: "",
    phone: "3173227172",
    facebook: "https://www.facebook.com/Amapolas-Buziracos-Rugby-Club-266240000248634/?__xts__[0]=68.ARBIAv6e1KFrX8KjDFq_vcWJkF_izQp_8cNwSgct2p4-_VDeea4gMVbbqDwuTJOi-AMAvFM9KjwUDjLED--P_MpdnNOTNLYWqEf1rPMYg5j8gF2v7WsRlmnXAUzgeU7pN4yyX9Y20SCzXzQLl-FrH0Q9gh3wMZP6lmZA-kl4Kj49QjBtBga5UoFn4FBznpb9tpeAwoZDzXgMg3KgLXKJj8CwcISVlb3Fmulp1bSFTT4uYyJjAXq7LgCKjNKd_OwULM1GmlJn-oTe",
    instagram: "https://www.instagram.com/amapolasrc/?hl=bg",
    twitter: "",
    comuna_id: 5,
  },
  {
    name: "El Bochinche",
    about: "Somos una organización de líderes, organizaciones e iniciativas juveniles; la cual busca el empoderamiento de niños, niñas, adolescentes y jovenes a través de la cultura, sexualidad, derechos humanos, medio ambiente y liderazgo para realizar procesos vivenciales de transformación en sus vidas, sus comunidades que generen un impacto positivo en sus territorios. Por medio del proyecto macro llamado Bochinche Por La paz como proceso de intervención e interacción psicosocial en las comunidades.",
    email: "fundacionbochinche@gmail.com",
    website: "",
    phone: "",
    facebook: "https://www.facebook.com/BOCHINCHEPOR/",
    instagram: "",
    twitter: "",
    comuna_id: 21,
  },
  {
    name: "Sporting Lions Cali",
    about: "Fomentamos el Fútbol como un deporte donde ayudará a los niños a crecer en buenos hábitos, salud y valores.",
    email: "sportinglionscolombia@gmail.com",
    website: "",
    phone: "317 5736983",
    facebook: "https://www.facebook.com/sportinglionscolombia/",
    instagram: "https://www.instagram.com/sportinglionscolombia/",
    twitter: "",
    comuna_id: 13,
  },
  {
    name: "Pacífico Futbol Cali",
    about: "Nos apasiona el futbol y motivamos a que niños, niñas y jóvenes de la comuna 13 de Cali practiquen este deporte como un estilo de vida saludable.",
    email: "",
    website: "",
    phone: "",
    facebook: "https://www.facebook.com/joseolivarc",
    instagram: "",
    twitter: "",
    comuna_id: 13,
  },
  {
    name: "La Fania Futbol Club",
    about: "El Club deportivo FANIA FUTBOL CLUB , viene promocionando la formación juvenil desde el componente deportivo con jóvenes del barrio charco azul, donde se benefician un promedio de 100 niños y jóvenes en edades entre 5 a 18 años con el objetivo de cambiar su perspectiva frente a la vida; Permitiendo que ellos sean un ejemplo para la comunidad inculcándoles valores y principios que les permita vivir la vida desde otra aspecto social.",
    email: "clubdeportivofaniafutbolclub@gmail.com",
    website: "http://fania-futbol.blogspot.com/",
    phone: "322 5945499",
    facebook: "https://www.facebook.com/Club-Deportivo-Fania-Futbol-Club-193323374779886/",
    instagram: "",
    twitter: "",
    comuna_id: 13,
  },
  # {
  #   name: "",
  #   about: "",
  #   email: "",
  #   website: "",
  #   phone: "",
  #   facebook: "",
  #   instagram: "",
  #   twitter: "",
  #   comuna_id: 1,
  # },
]

Community.create!(communities)
